### ISSUE TITLE
Question on ADMB license

### ISSUE THREAD

**Issue by yukio-takeuchi** [admb-project/admb#269]
For my personal use, I am trying to create a [homebrew](https://brew.sh) formula for ADMB  [here](https://github.com/yukio-takeuchi/homebrew-admb). This may potentially allow users of ADMB to set up ADMB easily on their Mac. Also as homebrew works on linux, it may potentially help linux users.
As homebrew formula requires the information of the license of the software to install and homebrew requires to choose any one of [them](https://spdx.org/licenses/), please help me to pick up an appropiate one. Currently I tentatively chose "BSD-3-Clause" [on 6th line](https://raw.githubusercontent.com/yukio-takeuchi/homebrew-admb/master/admb.rb), but I am not sure if it is OK.

**Comment by iantaylor-NOAA** [comment]
Hi @yukio-takeuchi, I just compared the text of https://github.com/admb-project/admb/blob/main/LICENSE.txt to https://spdx.org/licenses/BSD-3-Clause.html and I endorse your choice. 

I see there's a difference in "COPYRIGHT OWNER" vs "COPYRIGHT HOLDER" on this line https://github.com/admb-project/admb/blob/main/LICENSE.txt#L29 but otherwise they are identical and I think that difference is negligible in this context (recognizing that I am not a copyright expert).

Also, thank you for setting up the homebrew formula!

**Comment by yukio-takeuchi** [comment]
Hi @iantaylor-NOAA 

Thank you for your quick work.

Cheers.
