### ISSUE TITLE
dtu logo

### ISSUE THREAD

**Issue by johnoel** [admb-project/admb#46]

**Comment by johnrsibert** [comment]
You can pinch the logo from website. Here is the logo address (I think)
http://www.dtu.dk/-/media/DTU_Generelt/Navnetraek/DTU%20UK%20B1%20RGB.ashx?mh=100&mw=460

![dtulogo2_colour](https://cloud.githubusercontent.com/assets/5440370/16429960/37909144-3d2e-11e6-8dc1-864b0c7d17f2.png)

**Comment by johnoel** [comment]
Thanks John, Anders has already sent the link.

**Comment by gregorylburgess** [comment]
Updated.  Please review

**Comment by johnoel** [comment]
Text should be

Technical University of Denmark

instead of 

DTU.

**Comment by johnrsibert** [comment]
The acknowledgement links in the footer are messed up. DTU brings up NOAA.
The Fusion Creative website is defunct, so the logo should remain and the
live link deleted.

On Jul 13, 2016 5:08 PM, "johnoel" <notifications@github.com> wrote:

Text should be

Technical University of Denmark

instead of

DTU.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/admb-project/admb/issues/46#issuecomment-232522273>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AFMDckigGtB-oo1Q7F_-ZrrIOSa7Auq8ks5qVX3zgaJpZM4I_cSH>
.

**Comment by johnoel** [comment]
Greg will hopefully correct soon...

**Comment by johnoel** [comment]
Nevermind, fixed it, please check to see if okay...
